server:
  ssl:
    enabled: true
    protocol: TLS
    key-store-type: PKCS12
    key-store: classpath:keystore/langi_cert.p12
    key-alias: langi_cert
    enabled-protocols: TLSv1.2
    client-auth: need
    trust-store: classpath:keystore/truststore.p12


  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

spring:
  config:
    import: optional:secrets.yaml
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "main"